<template>
  <main>
    <section class="tagline">
      <h1><span class="font">PictureManager Cloud</span> is the new way to <span class="color">sync</span> and <span class="color">share</span> pictures</h1>
      <h2>Organize pictures into <span class="u">groups</span> and <span class="u">subgroups</span> with <span class="u">custom rules</span>.</h2>
    </section>

    <NuxtLink to="/">Go to the app</NuxtLink>


    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi non arcu risus quis. Morbi tristique senectus et netus et. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Diam sollicitudin tempor id eu nisl nunc mi ipsum. Pharetra diam sit amet nisl. Non tellus orci ac auctor augue. Arcu non odio euismod lacinia at quis risus. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Iaculis nunc sed augue lacus. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Enim nulla aliquet porttitor lacus. Dolor morbi non arcu risus quis varius. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Amet mauris commodo quis imperdiet massa tincidunt nunc. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Amet aliquam id diam maecenas ultricies mi eget mauris pharetra.

      Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Tincidunt eget nullam non nisi est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Eu volutpat odio facilisis mauris sit amet. Nulla facilisi nullam vehicula ipsum a arcu cursus. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Nisi scelerisque eu ultrices vitae auctor eu. Auctor augue mauris augue neque. Magnis dis parturient montes nascetur ridiculus. Phasellus egestas tellus rutrum tellus pellentesque. Id aliquet risus feugiat in. Sit amet nulla facilisi morbi tempus iaculis urna. Donec ac odio tempor orci dapibus ultrices in iaculis. Sem et tortor consequat id porta nibh venenatis. Ut diam quam nulla porttitor massa id. Felis eget nunc lobortis mattis. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Tristique risus nec feugiat in fermentum. Fames ac turpis egestas sed tempus urna.

      Non odio euismod lacinia at quis. Odio tempor orci dapibus ultrices in iaculis nunc sed. Elementum sagittis vitae et leo. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Lectus mauris ultrices eros in. Non enim praesent elementum facilisis leo vel fringilla. Enim nunc faucibus a pellentesque sit amet porttitor eget. Libero enim sed faucibus turpis in eu mi bibendum. Scelerisque eleifend donec pretium vulputate sapien nec sagittis. Enim diam vulputate ut pharetra sit amet aliquam id. Aliquam purus sit amet luctus venenatis lectus magna fringilla urna. Facilisi etiam dignissim diam quis enim. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Natoque penatibus et magnis dis parturient. Nibh tortor id aliquet lectus proin nibh nisl.

      Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Vitae justo eget magna fermentum iaculis eu. Ornare suspendisse sed nisi lacus sed viverra tellus. Dui ut ornare lectus sit. Ut etiam sit amet nisl purus. Volutpat est velit egestas dui id ornare arcu odio. Dignissim enim sit amet venenatis. Et tortor at risus viverra adipiscing at in tellus integer. Velit dignissim sodales ut eu sem integer vitae justo. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Commodo odio aenean sed adipiscing diam donec adipiscing.

      Tortor aliquam nulla facilisi cras fermentum odio. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Bibendum neque egestas congue quisque egestas diam in. Lectus mauris ultrices eros in cursus turpis. Euismod lacinia at quis risus sed vulputate odio ut enim. Sed vulputate mi sit amet mauris commodo quis imperdiet. Praesent elementum facilisis leo vel fringilla est. Ac odio tempor orci dapibus ultrices. Id ornare arcu odio ut sem nulla pharetra diam. Consequat semper viverra nam libero justo laoreet sit amet. Sit amet nisl purus in mollis nunc sed id semper. Arcu cursus vitae congue mauris rhoncus aenean. Risus commodo viverra maecenas accumsan lacus vel facilisis. Vestibulum sed arcu non odio euismod lacinia at. Mauris sit amet massa vitae tortor condimentum lacinia. Scelerisque felis imperdiet proin fermentum leo vel. Nec nam aliquam sem et. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida.

      Ornare lectus sit amet est. Tellus pellentesque eu tincidunt tortor aliquam nulla. Elit sed vulputate mi sit amet mauris commodo. Condimentum lacinia quis vel eros donec ac. Est pellentesque elit ullamcorper dignissim cras. Pellentesque habitant morbi tristique senectus et netus et malesuada. Semper feugiat nibh sed pulvinar. Ultricies leo integer malesuada nunc vel risus commodo. Sit amet nisl purus in mollis. Tempor nec feugiat nisl pretium fusce id velit ut. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Massa sapien faucibus et molestie ac feugiat sed lectus. Ipsum a arcu cursus vitae congue. Tempus quam pellentesque nec nam aliquam.

      Ipsum a arcu cursus vitae congue. Neque egestas congue quisque egestas diam in arcu. Fermentum iaculis eu non diam. Morbi quis commodo odio aenean. Orci phasellus egestas tellus rutrum tellus pellentesque. Cursus turpis massa tincidunt dui ut ornare lectus. Condimentum id venenatis a condimentum vitae sapien pellentesque. Etiam tempor orci eu lobortis elementum nibh tellus molestie. Habitasse platea dictumst quisque sagittis purus sit. Cursus sit amet dictum sit amet justo donec. Faucibus in ornare quam viverra orci sagittis eu volutpat. Sit amet volutpat consequat mauris nunc. Fames ac turpis egestas sed. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Vivamus arcu felis bibendum ut tristique et egestas. Cras sed felis eget velit aliquet sagittis. Nunc vel risus commodo viverra maecenas accumsan lacus vel. Eu lobortis elementum nibh tellus molestie. Auctor elit sed vulputate mi sit amet mauris commodo.

      Amet justo donec enim diam vulputate ut pharetra. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Adipiscing elit pellentesque habitant morbi tristique senectus et. Erat pellentesque adipiscing commodo elit at imperdiet dui. Nunc pulvinar sapien et ligula. Cras adipiscing enim eu turpis. Mi bibendum neque egestas congue quisque. Turpis cursus in hac habitasse platea dictumst. Varius morbi enim nunc faucibus a. Eget egestas purus viverra accumsan in nisl nisi scelerisque. Scelerisque varius morbi enim nunc faucibus a pellentesque. Vitae tortor condimentum lacinia quis vel. Tempor commodo ullamcorper a lacus vestibulum sed. Quisque id diam vel quam elementum. Pulvinar proin gravida hendrerit lectus a.

      Sit amet porttitor eget dolor morbi non. Mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing. Semper eget duis at tellus at urna condimentum. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. In nibh mauris cursus mattis molestie a. Non curabitur gravida arcu ac tortor. Augue lacus viverra vitae congue. Mi bibendum neque egestas congue quisque egestas diam. Non nisi est sit amet facilisis magna etiam tempor. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Sed cras ornare arcu dui vivamus arcu. Vel eros donec ac odio tempor orci dapibus.

      Odio ut enim blandit volutpat. Mattis nunc sed blandit libero. Facilisis magna etiam tempor orci eu. Est ante in nibh mauris cursus mattis. Tellus molestie nunc non blandit massa enim nec dui. Pulvinar etiam non quam lacus suspendisse faucibus. Donec pretium vulputate sapien nec sagittis aliquam malesuada. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Vulputate dignissim suspendisse in est ante. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Arcu felis bibendum ut tristique et egestas quis. Rhoncus est pellentesque elit ullamcorper dignissim. Viverra adipiscing at in tellus integer feugiat scelerisque. Facilisis leo vel fringilla est. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Tempor nec feugiat nisl pretium fusce. Odio aenean sed adipiscing diam donec adipiscing tristique risus. Scelerisque purus semper eget duis at tellus at urna.

      Urna molestie at elementum eu facilisis sed odio morbi quis. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Sit amet nisl purus in. Magna ac placerat vestibulum lectus. Augue lacus viverra vitae congue eu consequat ac felis. Eget aliquet nibh praesent tristique. Eu feugiat pretium nibh ipsum consequat nisl. Amet luctus venenatis lectus magna fringilla. Urna cursus eget nunc scelerisque viverra. Pellentesque habitant morbi tristique senectus et netus et. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Turpis in eu mi bibendum neque. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Hac habitasse platea dictumst vestibulum rhoncus. Urna condimentum mattis pellentesque id nibh. Morbi tristique senectus et netus. Ipsum dolor sit amet consectetur adipiscing elit. Senectus et netus et malesuada fames ac. Ut diam quam nulla porttitor.

      Proin libero nunc consequat interdum varius sit amet mattis. Libero justo laoreet sit amet cursus sit amet dictum sit. Commodo elit at imperdiet dui. Vel orci porta non pulvinar neque laoreet suspendisse. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Eu consequat ac felis donec et odio. Malesuada bibendum arcu vitae elementum curabitur. Ullamcorper sit amet risus nullam eget felis eget nunc. Urna nunc id cursus metus aliquam eleifend mi in nulla. Semper risus in hendrerit gravida rutrum quisque non. Orci eu lobortis elementum nibh tellus molestie nunc. Sit amet justo donec enim diam vulputate. Tellus elementum sagittis vitae et leo duis. Velit scelerisque in dictum non consectetur a erat nam at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Diam quis enim lobortis scelerisque fermentum dui. Turpis egestas maecenas pharetra convallis posuere morbi leo.

      Porttitor massa id neque aliquam. Est ante in nibh mauris cursus mattis molestie. Faucibus nisl tincidunt eget nullam non nisi est. Rutrum tellus pellentesque eu tincidunt. Arcu non sodales neque sodales ut etiam sit amet nisl. Mauris sit amet massa vitae. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Sit amet volutpat consequat mauris nunc. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Aliquet sagittis id consectetur purus ut faucibus. Sagittis vitae et leo duis ut diam quam. Lacinia at quis risus sed vulputate odio. Tortor posuere ac ut consequat semper viverra nam libero justo. Facilisis gravida neque convallis a cras semper auctor. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Elit eget gravida cum sociis natoque penatibus.

      Lacus sed viverra tellus in hac habitasse. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Diam donec adipiscing tristique risus nec. Amet dictum sit amet justo donec enim diam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Et netus et malesuada fames ac turpis egestas integer eget. Suspendisse in est ante in nibh mauris cursus. Urna nec tincidunt praesent semper feugiat nibh sed. Vulputate ut pharetra sit amet aliquam id. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Aliquam vestibulum morbi blandit cursus risus at ultrices mi tempus. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Ornare arcu odio ut sem nulla pharetra diam. Lorem ipsum dolor sit amet. Pellentesque habitant morbi tristique senectus et netus et. Aliquam ultrices sagittis orci a scelerisque purus semper.

      Quam nulla porttitor massa id neque aliquam. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Blandit massa enim nec dui. Tortor posuere ac ut consequat. Mattis rhoncus urna neque viverra justo. Arcu vitae elementum curabitur vitae. Non nisi est sit amet facilisis magna etiam tempor orci. Odio facilisis mauris sit amet massa vitae tortor condimentum lacinia. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Luctus accumsan tortor posuere ac ut consequat. Quam vulputate dignissim suspendisse in est ante in. Amet purus gravida quis blandit turpis cursus in. Tristique sollicitudin nibh sit amet commodo.

      Sit amet cursus sit amet dictum sit amet justo donec. Quis blandit turpis cursus in hac habitasse platea. Tincidunt arcu non sodales neque sodales. Lorem ipsum dolor sit amet. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Tellus elementum sagittis vitae et. Viverra nam libero justo laoreet. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Lorem mollis aliquam ut porttitor. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Velit ut tortor pretium viverra. Aliquet lectus proin nibh nisl condimentum. Auctor eu augue ut lectus arcu. Odio facilisis mauris sit amet massa vitae. Ipsum consequat nisl vel pretium lectus. Metus aliquam eleifend mi in nulla posuere. Vehicula ipsum a arcu cursus vitae congue mauris. Elit ut aliquam purus sit amet. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor.

      Nisl nisi scelerisque eu ultrices vitae. Auctor elit sed vulputate mi. Enim sit amet venenatis urna cursus eget. Pharetra convallis posuere morbi leo urna molestie at. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Sodales ut eu sem integer vitae justo eget magna. Hendrerit dolor magna eget est lorem ipsum dolor. A lacus vestibulum sed arcu. In aliquam sem fringilla ut morbi tincidunt augue interdum. Semper eget duis at tellus at urna condimentum mattis pellentesque. Quis enim lobortis scelerisque fermentum dui faucibus in. Tortor at risus viverra adipiscing at in tellus integer. Pellentesque sit amet porttitor eget dolor morbi non arcu. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Turpis tincidunt id aliquet risus feugiat in. Odio aenean sed adipiscing diam donec adipiscing. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Sit amet massa vitae tortor condimentum. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin aliquam.

      Amet aliquam id diam maecenas ultricies mi. Vel quam elementum pulvinar etiam. Vel fringilla est ullamcorper eget nulla. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Pellentesque nec nam aliquam sem et tortor consequat. Sagittis eu volutpat odio facilisis mauris sit. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. In nibh mauris cursus mattis molestie a iaculis at erat. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Sem integer vitae justo eget magna fermentum iaculis eu. Tempor nec feugiat nisl pretium fusce id velit ut. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Ornare massa eget egestas purus viverra. Eget mi proin sed libero enim sed faucibus. Nunc sed velit dignissim sodales ut eu sem. Quis commodo odio aenean sed adipiscing diam donec. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Pretium quam vulputate dignissim suspendisse. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant.

      Ac placerat vestibulum lectus mauris. Eu ultrices vitae auctor eu augue ut. Mattis aliquam faucibus purus in massa. Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Orci eu lobortis elementum nibh. Nam at lectus urna duis. Odio eu feugiat pretium nibh ipsum. Fermentum odio eu feugiat pretium nibh ipsum consequat. Sociis natoque penatibus et magnis dis parturient montes nascetur. Fusce ut placerat orci nulla. Elementum sagittis vitae et leo duis ut.

      Aliquam etiam erat velit scelerisque in dictum non consectetur. Lorem ipsum dolor sit amet consectetur adipiscing elit. Diam quis enim lobortis scelerisque fermentum dui faucibus in. A erat nam at lectus urna. Justo eget magna fermentum iaculis eu. Aliquam eleifend mi in nulla. Sagittis id consectetur purus ut. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Venenatis tellus in metus vulputate. Fusce id velit ut tortor pretium viverra suspendisse potenti nullam. Arcu felis bibendum ut tristique et egestas. Mattis rhoncus urna neque viverra.

      Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Sit amet venenatis urna cursus eget nunc scelerisque viverra. Dolor sit amet consectetur adipiscing. Amet justo donec enim diam vulputate ut. Urna molestie at elementum eu facilisis sed odio morbi quis. Id volutpat lacus laoreet non. Massa massa ultricies mi quis hendrerit dolor magna eget. Vel pretium lectus quam id leo in vitae. Pellentesque massa placerat duis ultricies lacus sed. Quis vel eros donec ac odio. Tellus integer feugiat scelerisque varius morbi. Vivamus arcu felis bibendum ut tristique et egestas.

      Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Ut sem viverra aliquet eget. Non blandit massa enim nec. Dui vivamus arcu felis bibendum. Aliquam ultrices sagittis orci a scelerisque purus. Tristique nulla aliquet enim tortor at auctor urna nunc. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Id donec ultrices tincidunt arcu. Faucibus et molestie ac feugiat sed. Tellus at urna condimentum mattis pellentesque id nibh. Consequat mauris nunc congue nisi vitae. Magnis dis parturient montes nascetur. Nibh cras pulvinar mattis nunc sed blandit libero. Viverra nibh cras pulvinar mattis nunc sed.

      Nunc sed blandit libero volutpat sed cras. Tincidunt lobortis feugiat vivamus at augue eget arcu. Porttitor leo a diam sollicitudin tempor id eu. Mi bibendum neque egestas congue quisque egestas diam. Phasellus egestas tellus rutrum tellus pellentesque eu. Sed blandit libero volutpat sed cras ornare. Feugiat vivamus at augue eget. Egestas purus viverra accumsan in nisl nisi scelerisque. Vulputate sapien nec sagittis aliquam malesuada. Enim diam vulputate ut pharetra sit amet aliquam id diam. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Neque convallis a cras semper auctor. Et malesuada fames ac turpis egestas sed tempus urna et. Augue eget arcu dictum varius duis at consectetur lorem donec. Fusce ut placerat orci nulla pellentesque dignissim enim sit amet. At urna condimentum mattis pellentesque id nibh tortor. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Accumsan tortor posuere ac ut consequat. Dictum non consectetur a erat nam at lectus urna. Et egestas quis ipsum suspendisse.

      Amet volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Morbi tristique senectus et netus et malesuada. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Duis convallis convallis tellus id. Ac odio tempor orci dapibus ultrices in iaculis nunc. Tellus elementum sagittis vitae et leo. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Est lorem ipsum dolor sit amet consectetur adipiscing. Ut aliquam purus sit amet. Tincidunt tortor aliquam nulla facilisi cras fermentum. Porttitor leo a diam sollicitudin tempor id eu nisl.

      Amet massa vitae tortor condimentum lacinia quis vel eros donec. Quis enim lobortis scelerisque fermentum. Hendrerit dolor magna eget est lorem ipsum dolor. Nulla facilisi cras fermentum odio. Sit amet est placerat in egestas erat imperdiet sed. Adipiscing elit pellentesque habitant morbi tristique. Quam adipiscing vitae proin sagittis nisl rhoncus. Facilisis volutpat est velit egestas dui id ornare. Porttitor massa id neque aliquam vestibulum. Cras sed felis eget velit aliquet sagittis id. Lacus laoreet non curabitur gravida arcu ac. Faucibus pulvinar elementum integer enim neque volutpat ac. Condimentum vitae sapien pellentesque habitant. Praesent semper feugiat nibh sed pulvinar. Nunc non blandit massa enim nec dui nunc mattis enim. Convallis posuere morbi leo urna. Vitae sapien pellentesque habitant morbi tristique senectus. Nibh mauris cursus mattis molestie.

      Commodo nulla facilisi nullam vehicula ipsum a. Cursus turpis massa tincidunt dui. Fermentum iaculis eu non diam. Vivamus arcu felis bibendum ut tristique. Pulvinar pellentesque habitant morbi tristique senectus et. Nisi quis eleifend quam adipiscing vitae. Id volutpat lacus laoreet non curabitur gravida arcu ac. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. Sit amet luctus venenatis lectus magna fringilla. Lectus mauris ultrices eros in cursus turpis massa. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Massa enim nec dui nunc mattis. Amet porttitor eget dolor morbi non arcu risus quis. Lobortis elementum nibh tellus molestie nunc.

      Elementum facilisis leo vel fringilla est ullamcorper eget nulla. Odio ut enim blandit volutpat maecenas. Etiam sit amet nisl purus in mollis nunc sed. At augue eget arcu dictum varius duis at. Pellentesque dignissim enim sit amet venenatis urna. Faucibus ornare suspendisse sed nisi lacus sed. Sed augue lacus viverra vitae congue eu consequat ac. Condimentum mattis pellentesque id nibh. Nunc faucibus a pellentesque sit amet porttitor. Convallis tellus id interdum velit laoreet id. Enim tortor at auctor urna nunc. Suscipit adipiscing bibendum est ultricies integer quis auctor. At risus viverra adipiscing at in tellus integer. Vulputate eu scelerisque felis imperdiet.

      Magna ac placerat vestibulum lectus mauris ultrices eros in. Ac turpis egestas maecenas pharetra. Integer malesuada nunc vel risus. Eu tincidunt tortor aliquam nulla facilisi cras. Enim tortor at auctor urna nunc id cursus metus. In nisl nisi scelerisque eu ultrices vitae auctor. Euismod elementum nisi quis eleifend. Nisl vel pretium lectus quam id leo in. Sed viverra tellus in hac habitasse. Urna condimentum mattis pellentesque id nibh tortor id aliquet. Fames ac turpis egestas sed tempus urna et pharetra.

      Volutpat commodo sed egestas egestas. In iaculis nunc sed augue lacus viverra vitae congue. Aliquam id diam maecenas ultricies mi eget mauris. Congue quisque egestas diam in arcu cursus euismod quis. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. In egestas erat imperdiet sed euismod nisi porta. Gravida arcu ac tortor dignissim convallis. Lacus luctus accumsan tortor posuere ac ut consequat semper. Nulla facilisi cras fermentum odio eu feugiat pretium nibh. Eu augue ut lectus arcu bibendum at varius vel. Sed adipiscing diam donec adipiscing tristique.

      Lacus sed turpis tincidunt id aliquet risus feugiat in ante. At risus viverra adipiscing at in tellus integer feugiat. Et netus et malesuada fames ac. Egestas erat imperdiet sed euismod nisi porta lorem mollis. Lacinia at quis risus sed vulputate odio ut. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Vulputate odio ut enim blandit volutpat maecenas volutpat. Morbi tristique senectus et netus et malesuada fames ac turpis. Sed velit dignissim sodales ut eu sem integer vitae justo. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Auctor elit sed vulputate mi sit. Suspendisse sed nisi lacus sed.

      Ornare quam viverra orci sagittis eu volutpat odio facilisis. Suspendisse in est ante in. Neque egestas congue quisque egestas diam in arcu cursus euismod. Risus pretium quam vulputate dignissim suspendisse. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Mollis nunc sed id semper risus in. Pellentesque elit eget gravida cum sociis natoque penatibus et. Bibendum arcu vitae elementum curabitur vitae nunc sed. Arcu bibendum at varius vel pharetra vel turpis. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium.

      Et tortor consequat id porta nibh. Fringilla phasellus faucibus scelerisque eleifend donec. Turpis egestas pretium aenean pharetra magna ac. Id venenatis a condimentum vitae sapien. Morbi tristique senectus et netus et malesuada. Tristique et egestas quis ipsum suspendisse ultrices gravida. Ultricies leo integer malesuada nunc vel risus. Lacinia at quis risus sed vulputate. Neque volutpat ac tincidunt vitae. Curabitur gravida arcu ac tortor. Nec tincidunt praesent semper feugiat nibh. Accumsan tortor posuere ac ut consequat semper viverra nam. Dictum non consectetur a erat. Tincidunt dui ut ornare lectus sit amet est. Mauris a diam maecenas sed enim ut.

      Imperdiet proin fermentum leo vel. Ac turpis egestas sed tempus urna et. Varius quam quisque id diam vel. Pretium vulputate sapien nec sagittis aliquam. Accumsan tortor posuere ac ut consequat semper viverra nam. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Turpis massa sed elementum tempus. Iaculis eu non diam phasellus vestibulum. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Facilisi etiam dignissim diam quis enim lobortis. Dui faucibus in ornare quam viverra orci. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper.

      Est ultricies integer quis auctor elit sed. Posuere sollicitudin aliquam ultrices sagittis orci a. Aliquet enim tortor at auctor. Odio pellentesque diam volutpat commodo sed egestas egestas. Eu sem integer vitae justo eget magna fermentum. Duis tristique sollicitudin nibh sit amet. Quisque egestas diam in arcu cursus euismod. Risus nullam eget felis eget nunc lobortis. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Ac turpis egestas maecenas pharetra convallis posuere. In vitae turpis massa sed elementum tempus egestas sed sed. Turpis massa sed elementum tempus egestas sed. Ornare suspendisse sed nisi lacus sed viverra tellus in hac. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin.

      Euismod in pellentesque massa placerat duis ultricies lacus. Nisl vel pretium lectus quam id leo. Senectus et netus et malesuada. Commodo quis imperdiet massa tincidunt nunc. Eu turpis egestas pretium aenean pharetra magna ac placerat. Magna eget est lorem ipsum. Lobortis feugiat vivamus at augue eget arcu dictum. Vel pharetra vel turpis nunc eget lorem. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Eu ultrices vitae auctor eu. Faucibus purus in massa tempor nec feugiat nisl pretium. Auctor eu augue ut lectus arcu bibendum at varius vel. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Dapibus ultrices in iaculis nunc sed augue lacus viverra vitae. Magna fringilla urna porttitor rhoncus dolor purus non enim. Ultricies mi quis hendrerit dolor magna eget.

      Scelerisque mauris pellentesque pulvinar pellentesque. Cursus risus at ultrices mi tempus imperdiet. Leo vel fringilla est ullamcorper eget nulla facilisi. Convallis aenean et tortor at. Sed faucibus turpis in eu. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Odio ut sem nulla pharetra diam sit. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Eros in cursus turpis massa tincidunt dui. Convallis a cras semper auctor neque vitae tempus. Rutrum tellus pellentesque eu tincidunt tortor. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a.

      A diam sollicitudin tempor id eu nisl nunc. Gravida dictum fusce ut placerat orci nulla. Orci a scelerisque purus semper eget. Tempus quam pellentesque nec nam aliquam sem. Ante metus dictum at tempor commodo ullamcorper a. Sed felis eget velit aliquet sagittis id consectetur. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Integer enim neque volutpat ac tincidunt vitae. Eu volutpat odio facilisis mauris sit amet massa. Et tortor consequat id porta nibh venenatis cras. Nibh tortor id aliquet lectus proin.

      Morbi tristique senectus et netus et. Tellus at urna condimentum mattis pellentesque id nibh. Iaculis urna id volutpat lacus laoreet non curabitur gravida. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Luctus accumsan tortor posuere ac ut consequat semper viverra. Tincidunt praesent semper feugiat nibh sed pulvinar proin. Molestie a iaculis at erat pellentesque adipiscing commodo elit. Pellentesque habitant morbi tristique senectus et. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Arcu bibendum at varius vel pharetra. Arcu dui vivamus arcu felis bibendum ut tristique. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Eget sit amet tellus cras adipiscing enim. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Molestie at elementum eu facilisis sed. Purus non enim praesent elementum facilisis leo. Nunc sed id semper risus in hendrerit gravida rutrum quisque.

      Quam adipiscing vitae proin sagittis nisl. Id interdum velit laoreet id. Interdum velit laoreet id donec ultrices tincidunt. Urna nec tincidunt praesent semper feugiat. Quam quisque id diam vel quam elementum. Consequat ac felis donec et odio pellentesque diam volutpat commodo. A cras semper auctor neque vitae tempus. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Nullam vehicula ipsum a arcu cursus vitae. Aliquam purus sit amet luctus venenatis. Odio ut enim blandit volutpat. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus.

      Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Est ullamcorper eget nulla facilisi etiam dignissim diam. Sodales neque sodales ut etiam. Elementum tempus egestas sed sed risus pretium quam vulputate dignissim. Facilisi cras fermentum odio eu. Sit amet massa vitae tortor condimentum lacinia quis. Sit amet nisl purus in mollis nunc sed id. Lorem sed risus ultricies tristique. Ipsum dolor sit amet consectetur. Odio aenean sed adipiscing diam.

      Magnis dis parturient montes nascetur ridiculus mus. Donec et odio pellentesque diam volutpat commodo sed egestas. Lacus luctus accumsan tortor posuere ac ut consequat. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Nec nam aliquam sem et tortor consequat id porta nibh. Lobortis mattis aliquam faucibus purus. Congue mauris rhoncus aenean vel elit scelerisque mauris. Quam pellentesque nec nam aliquam sem. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae proin.

      Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Netus et malesuada fames ac turpis. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Vivamus at augue eget arcu dictum varius duis. Nunc eget lorem dolor sed. Odio aenean sed adipiscing diam. Justo donec enim diam vulputate ut pharetra sit. Enim sit amet venenatis urna cursus eget nunc. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Amet nisl suscipit adipiscing bibendum est. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Sed ullamcorper morbi tincidunt ornare. Id donec ultrices tincidunt arcu non sodales. Congue eu consequat ac felis donec.

      In nibh mauris cursus mattis. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Amet porttitor eget dolor morbi non arcu risus quis. Est pellentesque elit ullamcorper dignissim cras. Scelerisque felis imperdiet proin fermentum. Commodo elit at imperdiet dui accumsan. Nec sagittis aliquam malesuada bibendum arcu. Turpis egestas integer eget aliquet. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Lobortis mattis aliquam faucibus purus in. Nisl condimentum id venenatis a condimentum vitae sapien. Malesuada nunc vel risus commodo. Purus ut faucibus pulvinar elementum integer enim neque. At augue eget arcu dictum varius duis at consectetur.

      Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Nulla facilisi morbi tempus iaculis urna. Aenean et tortor at risus viverra adipiscing at in tellus. Massa id neque aliquam vestibulum morbi. Amet massa vitae tortor condimentum lacinia. Risus pretium quam vulputate dignissim suspendisse in est ante in. At auctor urna nunc id cursus metus. Felis eget velit aliquet sagittis. Nulla porttitor massa id neque aliquam vestibulum morbi blandit. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Congue mauris rhoncus aenean vel elit.

      Vulputate mi sit amet mauris commodo quis imperdiet massa. Libero justo laoreet sit amet. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Aliquam faucibus purus in massa tempor nec feugiat. Ultricies mi eget mauris pharetra et ultrices neque ornare aenean. Ullamcorper morbi tincidunt ornare massa eget egestas. Felis bibendum ut tristique et egestas quis ipsum. Sit amet nisl purus in mollis nunc sed id. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Mattis aliquam faucibus purus in massa tempor nec feugiat. Donec ultrices tincidunt arcu non sodales neque sodales ut. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Massa enim nec dui nunc mattis. Non sodales neque sodales ut etiam sit amet nisl purus. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Nisl purus in mollis nunc. Facilisis gravida neque convallis a cras semper auctor neque.

      Lacus sed turpis tincidunt id. Tellus cras adipiscing enim eu turpis. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Ante metus dictum at tempor commodo ullamcorper a lacus. Nibh sit amet commodo nulla. Velit ut tortor pretium viverra suspendisse. Neque gravida in fermentum et sollicitudin ac. Nibh ipsum consequat nisl vel. Senectus et netus et malesuada fames. Leo integer malesuada nunc vel. Suspendisse in est ante in nibh mauris cursus. Nisl nisi scelerisque eu ultrices.

      Dictumst quisque sagittis purus sit. Velit sed ullamcorper morbi tincidunt ornare massa eget. Vulputate mi sit amet mauris commodo quis. Faucibus interdum posuere lorem ipsum dolor sit amet. In hac habitasse platea dictumst quisque. Aliquet porttitor lacus luctus accumsan tortor posuere. Posuere ac ut consequat semper viverra nam libero. Tempus quam pellentesque nec nam. Mauris cursus mattis molestie a iaculis at erat pellentesque. Ut pharetra sit amet aliquam. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Ornare aenean euismod elementum nisi quis eleifend quam. Nibh tellus molestie nunc non blandit massa enim. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Nisl suscipit adipiscing bibendum est ultricies integer. Faucibus a pellentesque sit amet porttitor eget. Morbi non arcu risus quis varius quam. Arcu cursus euismod quis viverra. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. At auctor urna nunc id cursus metus aliquam eleifend mi.

      Tempus egestas sed sed risus pretium quam vulputate. Libero nunc consequat interdum varius sit amet mattis. Blandit libero volutpat sed cras ornare. Mauris nunc congue nisi vitae. Senectus et netus et malesuada fames. Nulla aliquet enim tortor at auctor urna. Ante metus dictum at tempor commodo ullamcorper. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Integer quis auctor elit sed vulputate. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Turpis in eu mi bibendum. Imperdiet proin fermentum leo vel orci. Sed sed risus pretium quam. Bibendum neque egestas congue quisque egestas diam in. In massa tempor nec feugiat nisl. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Velit scelerisque in dictum non consectetur a erat nam. Velit laoreet id donec ultrices tincidunt arcu non.

      Risus pretium quam vulputate dignissim suspendisse in. Bibendum ut tristique et egestas quis ipsum suspendisse. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Hac habitasse platea dictumst quisque sagittis purus sit. Amet nisl purus in mollis nunc sed id semper. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Dignissim suspendisse in est ante. In nulla posuere sollicitudin aliquam ultrices sagittis orci. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Urna cursus eget nunc scelerisque viverra mauris in aliquam. Massa id neque aliquam vestibulum morbi blandit cursus risus. Id aliquet lectus proin nibh nisl. Enim facilisis gravida neque convallis a. Amet justo donec enim diam vulputate ut pharetra sit amet.

      Sed odio morbi quis commodo. Nisl purus in mollis nunc sed id. Sed augue lacus viverra vitae congue eu consequat ac felis. Interdum velit laoreet id donec. Lorem ipsum dolor sit amet consectetur adipiscing. Dictum fusce ut placerat orci nulla pellentesque. Consectetur adipiscing elit pellentesque habitant morbi tristique. At tempor commodo ullamcorper a. Porttitor leo a diam sollicitudin. Interdum consectetur libero id faucibus nisl tincidunt. Molestie a iaculis at erat pellentesque. Nullam ac tortor vitae purus faucibus ornare suspendisse. Libero enim sed faucibus turpis in eu mi bibendum. Mattis ullamcorper velit sed ullamcorper morbi. Aliquam faucibus purus in massa tempor nec feugiat nisl. Eget nullam non nisi est. Enim praesent elementum facilisis leo vel. Eget mi proin sed libero enim sed faucibus. Sed egestas egestas fringilla phasellus faucibus scelerisque.</p>
  </main>
</template>

<script setup lang="ts">

definePageMeta({
  layout: 'default'
})

useSeoMeta({
  title: 'PMCloud Overview',
  ogTitle: 'Overview',
  description: 'An efficient cloud based picture manager that supports automatic grouping of pictures into custom hierarchies, while allowing users to share groups together.',
  ogDescription: 'An efficient cloud based picture manager that supports automatic grouping of pictures into custom hierarchies, while allowing users to share groups together.',
  ogImage: 'https://example.com/image.png'
})

</script>

<style scoped lang="stylus">
section.tagline
  background-color var(--primary-100)
  padding-top 10rem
  padding-bottom 6rem
  h1, h2
    font-family Inter
    margin auto
    text-align center
    max-width 75vw
  h1
    font-weight 800
    font-size 4.3rem
    line-height 5.5rem
    filter drop-shadow(.5rem .5rem 2rem hsla(215, 25%, 27%, .5))
  h2
    margin-top 1rem
    font-weight 500
    font-size 1.9rem
  span.color
    color var(--orange-600)
    font-weight 900
  span.u
    text-decoration underline
  span.font
    font-family 'Noto Serif Ethiopic'
    font-weight 800
</style>
